### ISSUE TITLE
ccos_disk_tool does not open device files.

### ISSUE THREAD

**Issue by tschak909** [BOOtak/CCOS-disk-utils#11]
This is an example of trying to be smarter than the user; to save them from themselves. 

![image](https://user-images.githubusercontent.com/2759782/188539236-d2c06aac-580f-4e7c-bbaa-7c54a0c182c4.png)

STOP IT.

Everything in UNIX is a file, this includes block devices :)

Remove the offending code that tries to check for a file and you'll find this magically works. :)

-Thom

**Comment by BOOtak** [comment]
Sure, I'll fix it. The only reason it was added was to check it's not a directory
