### ISSUE TITLE
Support imaged hard disks from GRiD 2101

### ISSUE THREAD

**Issue by tschak909** [BOOtak/CCOS-disk-utils#9]
I am participating in a restoration of a massive hard disk dump of files, including the CCOS versions of the PLM, Pascal, and Assembler. This tool currently can't read this image (am guessing because of the partition table at the beginning, and removing it doesn't seem to help. 

What could I do here to help scoot this along?

-Thom

**Comment by BOOtak** [comment]
Hi, you're right, the reason this tool can't read HDD image is that it doesn't work with partitions.

Currently I am not indended to add partitions support, so for now you can extract partitions from the image and try to work with them separately. The one way to do this is following:

```bash
sudo losetup /dev/loop0 image.img
sudo dd if=/dev/loop0p1 of=image1.img bs=512
sudo dd if=/dev/loop0p2 of=image2.img bs=512
sudo losetup -d /dev/loop0
```

Surprisingly, 7zip can extract partitions from the image, so you can unpack partitions with 7zip and open them with this tool.

Let me know if you had any success with this!

**Comment by tschak909** [comment]
it is not an IBM partition table. 

And simply removing it from the image doesn't allow it to be read.

Do you have any notes for the filesystem? Failing that, I do have the source code to GBridge.

-Thom

**Comment by BOOtak** [comment]
Unfortunately, I don't have any notes aside from slides to my talk on the topic (in Russian) (https://docs.google.com/presentation/d/1B8uzHvDOABl6Ut9hkim2ZGHw16zPD8_9fL3_q0fmtVQ/edit?usp=sharing) and code itself.

You can find most of the info on filesystem structure in https://github.com/BOOtak/CCOS-disk-utils/blob/master/ccos_private.h

There
* `ccos_inode_t` is a 0x200 byte block with file info (name, length, checksums, blocks with file content, etc.)
* `ccos_content_inode_t` is an optional block listing all extra file content blocks
* `ccos_bitmask_t` is a special block (usually # 0x120) with a bitmask (indicating free/used blocks on disc)
* `ccos_block_data_t` is a special structure linking file & content blocks into double-linked list

Can you provide me with the image you're trying to open? I'll try to look into it.

On the side note, what `file <image>.img` tells? And also, did you try to open it with 7zip? I successfully opened .IMG where `file` said it was `DOS/MBR boot sector`, with two GRiD-OS partitions inside.

**Comment by tschak909** [comment]
The disk image comes from a GRiD 2101 that was attached to a GRiD Compass.

I can send it to your email, with the caveat that it can't be shared. It
contains personal data that we are trying to scrub away, first.

-Thom

**Comment by BOOtak** [comment]
OK, I can assure you it won't be shared, you can send it to
***@***.***

пн, 15 авг. 2022 г. в 17:50, Thomas Cherryhomes ***@***.***>:

**Comment by tschak909** [comment]
darn, github is scrubbing...

here. [tmp.MFMv122.zip](https://github.com/BOOtak/CCOS-disk-utils/files/9338530/tmp.MFMv122.zip)

**Comment by BOOtak** [comment]
@tschak909 Got it, thanks! I'll look into it!

**Comment by BOOtak** [comment]
Ok. I looked into it. It seems that the image you've provided is interleaved, i.e blocks are placed out of order.

I was able to restore interleaving orded, and I wrote a simle Python script to deinterleave the image you provided.

https://gist.github.com/BOOtak/4df7a497b9b5fe09957326b6c1795142

After deinterleaving, you can extract partitions as I described previously (https://github.com/BOOtak/CCOS-disk-utils/issues/9#issuecomment-1214908487)

And work with them with my tool. I was able to successfully extract partitions and list files in them.

Unfortunately my tool crashes when tries to print image contents with double-free, but that's another issue with how I handle bitmask in the large images. I'll try to fix that also

I'll send deinterleaved image and unpacked partitions to the email in your profile

**Comment by BOOtak** [comment]
> Unfortunately my tool crashes when tries to print image contents

Just fix that, please try this!

**Comment by tschak909** [comment]
yup awesome was able to pull everything from the image! :)

And now...

![plm_worky](https://user-images.githubusercontent.com/2759782/184987593-0f429ec6-204e-4e74-a560-1f1c0f3841c6.png)

-Thom

**Comment by Bs0Dd** [comment]
We also have a Qt graphical utility based on this library to make it easier to work with images. Just recently completed there the ability to work with hard drives.

https://github.com/Bs0Dd/GRiDISKCOM
